--Dummy data which is created by mockaroo.com
--concat(lower(field('Username')),"@","dymmy",".com")
--This script used in the mockaroo.com site to create email address from Username.
insert into userTable (User_id, Username, Email, Password) values (1, 'Aguistin', 'aguistin@dymmy.com', 'amet justo');
insert into userTable (User_id, Username, Email, Password) values (2, 'Peggi', 'peggi@dymmy.com', 'vel augue');
insert into userTable (User_id, Username, Email, Password) values (3, 'Homere', 'homere@dymmy.com', 'euismod');
insert into userTable (User_id, Username, Email, Password) values (4, 'Oralla', 'oralla@dymmy.com', 'iaculis');
insert into userTable (User_id, Username, Email, Password) values (5, 'Velvet', 'velvet@dymmy.com', 'vitae');
insert into userTable (User_id, Username, Email, Password) values (6, 'Berti', 'berti@dymmy.com', 'suspendisse potenti');
insert into userTable (User_id, Username, Email, Password) values (7, 'Patrizio', 'patrizio@dymmy.com', 'consectetuer');
insert into userTable (User_id, Username, Email, Password) values (8, 'Abraham', 'abraham@dymmy.com', 'et');
insert into userTable (User_id, Username, Email, Password) values (9, 'Marcelline', 'marcelline@dymmy.com', 'praesent id');
insert into userTable (User_id, Username, Email, Password) values (10, 'Morse', 'morse@dymmy.com', 'vel nisl');
insert into userTable (User_id, Username, Email, Password) values (11, 'Noemi', 'noemi@dymmy.com', 'adipiscing');
insert into userTable (User_id, Username, Email, Password) values (12, 'Mercedes', 'mercedes@dymmy.com', 'ultrices');
insert into userTable (User_id, Username, Email, Password) values (13, 'Herman', 'herman@dymmy.com', 'sit amet');
insert into userTable (User_id, Username, Email, Password) values (14, 'Carroll', 'carroll@dymmy.com', 'nulla');
insert into userTable (User_id, Username, Email, Password) values (15, 'Ezekiel', 'ezekiel@dymmy.com', 'lacus curabitur');
insert into userTable (User_id, Username, Email, Password) values (16, 'Terrill', 'terrill@dymmy.com', 'consequat lectus');
insert into userTable (User_id, Username, Email, Password) values (17, 'Thaddus', 'thaddus@dymmy.com', 'semper');
insert into userTable (User_id, Username, Email, Password) values (18, 'Mattias', 'mattias@dymmy.com', 'nascetur ridiculus');
insert into userTable (User_id, Username, Email, Password) values (19, 'Ellissa', 'ellissa@dymmy.com', 'nec');
insert into userTable (User_id, Username, Email, Password) values (20, 'Papageno', 'papageno@dymmy.com', 'dictumst maecenas');
insert into userTable (User_id, Username, Email, Password) values (21, 'Jaymie', 'jaymie@dymmy.com', 'tincidunt eget');
insert into userTable (User_id, Username, Email, Password) values (22, 'Guglielma', 'guglielma@dymmy.com', 'sed nisl');
insert into userTable (User_id, Username, Email, Password) values (23, 'Gusti', 'gusti@dymmy.com', 'in tempus');
insert into userTable (User_id, Username, Email, Password) values (24, 'Tracey', 'tracey@dymmy.com', 'consequat nulla');
insert into userTable (User_id, Username, Email, Password) values (25, 'Jackson', 'jackson@dymmy.com', 'eu');
insert into userTable (User_id, Username, Email, Password) values (26, 'Craggy', 'craggy@dymmy.com', 'sit amet');
insert into userTable (User_id, Username, Email, Password) values (27, 'Patrica', 'patrica@dymmy.com', 'mattis');
insert into userTable (User_id, Username, Email, Password) values (28, 'Cherianne', 'cherianne@dymmy.com', 'lectus aliquam');
insert into userTable (User_id, Username, Email, Password) values (29, 'Chantal', 'chantal@dymmy.com', 'bibendum');
insert into userTable (User_id, Username, Email, Password) values (30, 'Homer', 'homer@dymmy.com', 'aenean');
insert into userTable (User_id, Username, Email, Password) values (31, 'Arleen', 'arleen@dymmy.com', 'ipsum');
insert into userTable (User_id, Username, Email, Password) values (32, 'Mathilde', 'mathilde@dymmy.com', 'placerat praesent');
insert into userTable (User_id, Username, Email, Password) values (33, 'Ofilia', 'ofilia@dymmy.com', 'cum');
insert into userTable (User_id, Username, Email, Password) values (34, 'Dmitri', 'dmitri@dymmy.com', 'faucibus orci');
insert into userTable (User_id, Username, Email, Password) values (35, 'Cherise', 'cherise@dymmy.com', 'justo sit');
insert into userTable (User_id, Username, Email, Password) values (36, 'Raymund', 'raymund@dymmy.com', 'in eleifend');
insert into userTable (User_id, Username, Email, Password) values (37, 'Vinnie', 'vinnie@dymmy.com', 'at velit');
insert into userTable (User_id, Username, Email, Password) values (38, 'Hagen', 'hagen@dymmy.com', 'tincidunt lacus');
insert into userTable (User_id, Username, Email, Password) values (39, 'Dorisa', 'dorisa@dymmy.com', 'accumsan felis');
insert into userTable (User_id, Username, Email, Password) values (40, 'Carmon', 'carmon@dymmy.com', 'nunc');
insert into userTable (User_id, Username, Email, Password) values (41, 'Susanna', 'susanna@dymmy.com', 'at turpis');
insert into userTable (User_id, Username, Email, Password) values (42, 'Sanford', 'sanford@dymmy.com', 'in');
insert into userTable (User_id, Username, Email, Password) values (43, 'Claybourne', 'claybourne@dymmy.com', 'nulla facilisi');
insert into userTable (User_id, Username, Email, Password) values (44, 'Brina', 'brina@dymmy.com', 'vitae');
insert into userTable (User_id, Username, Email, Password) values (45, 'Jacinda', 'jacinda@dymmy.com', 'ut');
insert into userTable (User_id, Username, Email, Password) values (46, 'Minette', 'minette@dymmy.com', 'nullam');
insert into userTable (User_id, Username, Email, Password) values (47, 'Dorette', 'dorette@dymmy.com', 'rhoncus aliquam');
insert into userTable (User_id, Username, Email, Password) values (48, 'Hobart', 'hobart@dymmy.com', 'lacus purus');
insert into userTable (User_id, Username, Email, Password) values (49, 'Obediah', 'obediah@dymmy.com', 'augue a');
insert into userTable (User_id, Username, Email, Password) values (50, 'Magdaia', 'magdaia@dymmy.com', 'nam congue');

insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (7, 1, 'Gelatine Leaves - Bulk', '2017-08-12 01:07:22', '7.08');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (30, 2, 'Evaporated Milk - Skim', '2017-07-20 21:31:21', '0.24');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (19, 3, 'Mustard - Pommery', '2016-11-03 02:01:31', '3.72');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (11, 4, 'Veal - Sweetbread', '2017-07-22 02:02:43', '0.82');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (16, 5, 'Cheese - Comtomme', '2016-11-04 19:37:35', '1.67');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (36, 6, 'Wine - Shiraz South Eastern', '2017-03-14 21:00:51', '1.37');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (28, 7, 'Bread - English Muffin', '2017-03-30 19:55:58', '6.24');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (19, 8, 'Container - Clear 16 Oz', '2017-06-16 16:13:06', '0.28');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (35, 9, 'Onions - Green', '2016-11-08 19:33:38', '3.72');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (44, 10, 'Ecolab Crystal Fusion', '2017-07-13 19:58:11', '9.24');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (33, 11, 'Appetizer - Escargot Puff', '2017-07-02 16:17:07', '2.38');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (8, 12, 'Corn Syrup', '2017-01-12 06:49:43', '7.21');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (10, 13, 'Peppercorns - Green', '2017-08-20 07:28:19', '5.01');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (11, 14, 'Ecolab Silver Fusion', '2017-06-25 05:58:13', '0.28');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (31, 15, 'Assorted Desserts', '2017-05-30 10:42:59', '8.13');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (22, 16, 'Lettuce - Baby Salad Greens', '2017-08-16 03:06:55', '0.76');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (5, 17, 'Garbage Bags - Clear', '2017-05-11 08:34:34', '5.14');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (5, 18, 'Pears - Bosc', '2017-02-14 23:48:29', '4.20');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (10, 19, 'Beans - French', '2017-01-11 20:29:48', '8.52');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (16, 20, 'Fish - Atlantic Salmon, Cold', '2017-01-09 07:06:05', '9.32');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (41, 21, 'Longos - Greek Salad', '2016-12-31 20:03:25', '2.21');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (43, 22, 'Amaretto', '2017-06-28 06:44:37', '9.58');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (19, 23, 'Wine - Clavet Saint Emilion', '2016-11-25 15:26:50', '0.42');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (16, 24, 'Seaweed Green Sheets', '2016-11-20 14:38:11', '3.06');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (5, 25, 'Red Cod Fillets - 225g', '2017-05-02 23:20:53', '6.97');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (27, 26, 'Soup - Cream Of Potato / Leek', '2017-01-19 01:23:41', '3.20');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (43, 27, 'Cake - Mini Cheesecake', '2017-09-10 01:38:13', '5.32');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (32, 28, 'Coke - Diet, 355 Ml', '2017-01-20 01:32:07', '8.54');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (46, 29, 'Pastry - Choclate Baked', '2016-10-17 02:21:21', '6.20');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (34, 30, 'Pears - Anjou', '2017-08-19 08:09:46', '8.93');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (34, 31, 'Garbag Bags - Black', '2016-12-16 22:45:31', '3.03');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (48, 32, 'Veal Inside - Provimi', '2016-11-24 05:41:16', '2.15');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (28, 33, 'Nut - Cashews, Whole, Raw', '2017-07-13 13:00:23', '4.67');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (17, 34, 'Turkey - Breast, Double', '2017-06-10 10:22:28', '8.79');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (25, 35, 'Fenngreek Seed', '2016-12-28 14:25:07', '8.25');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (30, 36, 'Chocolate - White', '2017-05-12 15:06:30', '2.44');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (38, 37, 'Wine - Zinfandel Rosenblum', '2017-06-30 12:50:45', '5.43');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (14, 38, 'Rice - Brown', '2017-05-11 06:31:57', '9.09');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (49, 39, 'Olives - Green, Pitted', '2017-09-14 01:57:54', '2.62');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (32, 40, 'Spice - Peppercorn Melange', '2016-11-11 09:56:45', '4.05');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (19, 41, 'Browning Caramel Glace', '2017-06-22 00:14:53', '3.24');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (43, 42, 'Ice Cream - Life Savers', '2017-04-29 11:55:40', '8.79');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (49, 43, 'Cilantro / Coriander - Fresh', '2017-07-03 23:46:19', '6.37');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (13, 44, 'Coffee - Decafenated', '2017-02-14 17:58:26', '9.71');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (40, 45, 'Cookies - Oreo, 4 Pack', '2016-09-22 20:31:17', '6.52');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (8, 46, 'Beer - Rickards Red', '2017-06-07 10:30:32', '2.55');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (44, 47, 'Foam Espresso Cup Plain White', '2017-01-23 07:46:52', '9.86');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (46, 48, 'Cabbage - Nappa', '2017-05-09 05:54:26', '6.16');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (47, 49, 'Frangelico', '2017-02-27 11:31:02', '2.03');
insert into shared_burden (User_id, Item_id, Item_name, T_timetamp, Price ) values (14, 50, 'Flounder - Fresh', '2017-06-03 13:52:56', '9.93');